Haseeb3927/Booster

.gitignore, server/api.js
=> DB updated and post query for new user

server/api.js
Added methods to get an energiser by id params, search query and also added a post method of adding energiser
Added methods to get an energiser by id params, search query and also added a post method of adding energiser
Fixes #1
- [* ] My code follows the style guidelines of this project
- [ * ] I have carefully reviewed my own code
- [ * ] I have commented my code
- [ * ] I have updated any documentation
=> Added Get and Post request In api.js-HASEEB_KHALIL

server/api.js
I could see everyone else's changes in my local code but not mine. That's why sending these changes again 
#15 
Fixes #1
=> Updated endpoints-HASEEB-KHALIL

client/src/components/CardsCarousel/CardCarousel.js, client/src/components/CardsCarousel/CardsSection.js, client/src/components/CardsCarousel/Energise.js, client/src/components/Jumbotron/Hero.js, client/src/pages/Home.js, package-lock.json, package.json
Error fix
Fixed some errors on cards
=> Fix a few errors on cards

client/src/App.js, client/src/components/CardsCarousel/CardCarousel.js, client/src/components/Footer/Footer.js, client/src/components/Header/Navbar.js, client/src/pages/Energise.js, client/src/pages/Home.js
27-Footer-Selahaddin
A footer has been added to both pages, Home and Energise. 
Energise.js has been moved to the Pages folder. -Important!-
Fixes:
(https://github.com/Haseeb3927/Booster/projects/1#card-79304745)
=> Style Footer - Selahaddin

client/src/components/CardsCarousel/CardCarousel.js, client/src/components/Footer/Footer.js, client/src/pages/Home.js
Footer - Selahaddin
This is a closed branch, mistakenly send another pr. Can be merged before the footer-component branch's pr (#27  ) to avoid conflicts.
=> Add footer file - Selahaddin - Merge first!

client/src/App.js, client/src/components/CardsCarousel/CardCarousel.js, client/src/components/Footer/Footer.js, client/src/components/Header/Navbar.js, client/src/components/Timer.js, client/src/pages/Energise.js, client/src/pages/Home.js, package-lock.json, package.json
29- Timer - Selahaddin
A timer of 15- minutes was added to the energise page.
=> Add timer - Selahaddin

client/src/App.js, client/src/components/CardsCarousel/CardCarousel.js, client/src/components/Footer/Footer.js, client/src/components/Header/Navbar.js, client/src/components/Timer.js, client/src/pages/Energise.js, client/src/pages/Home.js, package-lock.json, package.json
Fix the filter in the energise page - Selahaddin
Changed the type of ID to int to fix the filter.
=> Fix filter - Selahaddin

client/src/pages/Energise.js, server/api.js
=> added to db images for energisers

client/src/components/CardsCarousel/CardCarousel.js, client/src/components/CardsCarousel/CardsSection.js, client/src/components/CardsCarousel/Vote.js, client/src/components/Footer/Footer.js, client/src/components/Jumbotron/Hero.js
Vote Component Added-Adem
Vote Component Added.And also some changes(background image,heading,paragraph..) on homepage and Footer
Fixes #1
=> added vote component on FE-Adem

server/api.js
Likes and Dislikes can be updated in backend using these endpoints.
PUT /energiser/:energiserId/like
PUT /energiser/:energiserId/dislike
=> Added-likes-and-dislikes-endpoints_HASEEB-KHALIL

server/api.js
Added an endpoint to get TEN most popular energisers depending on their likes.
GET "/energisers/popular"
=> Added-most-popular-energisers-endpoint_HASEEB-KHALIL

server/api.js
Added image entity in SQL queries for the required endpoints.
=> Added-image-entity-in-SQL-queries_HASEEB-KHALIL

server/api.js
The host can create a random code to share with users. They can join the energiser page using the join button and 7 digit code provided by the host. They will see a synced timer that will display the same time to everyone.
=> Host-And-Join-Functional-endpoints_HASEEB-KHALIL

client/src/components/CardsCarousel/Vote.js
=> Vote component connected with BE

server/api.js
=> Api put endpoint changes

client/src/App.js, client/src/pages/Cards.js, client/src/pages/Energise.js, client/src/pages/Host.js, server/app.js
Made host button work with backend to get the energiser with a random code.
=> Feature-hosted-energiser_HASEEB-KHALIL

client/src/components/Cards.js
A variable name is corrected in the card component.
=> Fix card filter variable

client/src/App.js, client/src/components/CardsCarousel/PopularEnergisers.js, client/src/components/CardsCarousel/Vote.js, client/src/pages/Energise.js, client/src/pages/Host.js, server/app.js
=> CORS-error-fixed_HASEEB-KHALIL

client/src/index.html
Fixing with
`<meta
http-equiv="Content-Security-Policy"
content="
connect-src 'self';
default-src 'none';
img-src 'self';
manifest-src 'self';
script-src-elem 'self';
style-src-elem 'self';
">
`
=> Fixing-with-Meta-Tag_HASEEB-KHALIL

client/src/components/Cards.js, client/src/index.html
=> Removed-Meta-tag_HASEEB-KHALIL

.eslintrc.json, package-lock.json, package.json
Name your PR like this:Socket Dependencies-Adem Alagoz
added socket io to package.json for online users displaying and "linebreak-style":0 to .eslintrc.json
Fixes #1
- [ x ] My code follows the style guidelines of this project
- [ x ] I have carefully reviewed my own code
- [ x] I have commented my code
- [ x] I have updated any documentation
=> Added socket io dependencies to package.json-eslint linebreak-Adem

client/src/App.js
=> Fixed app.js api for socket-Adem

client/src/pages/Energise.js, client/src/pages/Host.js
=> Changed onlinecount place-Adem

client/src/index.html
Adds responsive meta tag to the index HTML file
Fixes #66
=> Add-viewport-meta-tag-Selahaddin

client/src/App.js, client/src/components/Footer/Footer.js, client/src/pages/Faq.js
Fixes #1 FAQ Page created
- [ x] My code follows the style guidelines of this project
- [ x] I have carefully reviewed my own code
- [ x] I have commented my code
- [ x] I have updated any documentation
=> FAQ page created - Abiya

README.md
Added ReadMe File to support current project
=> Correct-ReadMe-added_HASEEB-KHALIL

client/src/components/CardsCarousel/PopularEnergisers.js, client/src/index.css
Popular energiser slider is now responsive for tablets and mobile phones
=> Made-popular-energisers-slider-responsive_HASEEB-KHALIL

client/src/components/Jumbotron/Hero.js, client/src/components/SearchBar/SearchBar.js, client/src/components/Theme.js, client/src/pages/AllEnergisers.js
Makes the hero on the home page more responsive. Changes font sizes, button sizes.
Fixes #1
=> Make-jumbotron-more-responsive-selahaddin

client/src/components/Header/Navbar.js, client/src/components/Timer.js, client/src/index.css, client/src/pages/AllEnergisers.js, client/src/pages/Energise.js, client/src/pages/Host.js
Makes the energiser page mobile responsive.
=> Feature-responsive-energise-page_Selahaddin

client/src/components/Theme.js, client/src/index.css, client/src/pages/Energise.js, client/src/pages/Host.js
Fixes the game code button's case insensitivty.
=> Fix-game-code-button-case-sensitivity_Selahaddin

client/src/components/Blog/Blog.js, client/src/pages/AllEnergisers.js, client/src/pages/Faq.js, client/src/pages/Host.js
Makes all energisers and faq page responsive
=> Make-faq-and-energiser-page-responsive_Selahaddin
